server:
  port: 9003

spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavaMaxLi/SpringClould.git
          #search-paths: serverPath
---
spring:
  profiles: dev
  application:
    name: provider01-dev