server:
  port: 8080

spring:
  application:
    name: springcloud-consumer

#Eureka配置
eureka:
  client:
    register-with-eureka: false   #不向注册中心注册自己
    service-url:
      defaultZone: http://localhost:8002/eureka/,http://localhost:8003/eureka/,http://localhost:8004/eureka/
feign:
  hystrix:
    enabled: true


