server:
  port: 8001

mybatis:
  type-aliases-package: com.bean.*
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


spring:
  application:
    name: springcloud-provider
  datasource:     #mybatis配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root123456